import type { Metadata } from "next";
import { Exo, Inter } from "next/font/google";
import "./globals.css";

const geistSans = Exo({
  variable: "--font-Exo",
  subsets: ["latin"],
});

const geistMono = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
